server:
  port: 9094
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: auth-service # 服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/cloudmusic
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@Aa123456'
  cloud:
    nacos:
      server-addr: http://common-nacos-dev.magestack.cn:8848
      discovery:
        cluster-name: FJ # 集群名称
        ip: 8.210.250.29 # 注册到nacos的ip与端口
        port: 9094
  redis:
    host: localhost
    port: 6379
    database: 0
  mail:
    host: smtp.qq.com
    username: flying_pig_z@qq.com
    password:
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true


#??sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#swagger配置
swagger:
  title: "鉴权模块"
  description: "鉴权模块接口"
  base-package: com.flyingpig.cloudmusic.auth
  enabled: true
  version: 1.0.0
#feign远程调用配置
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  sentinel:
    enabled: true