server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: http://47.122.56.65:8848 # nacos地址
    gateway:
      #从gateway路由的所有请求都会带上origin头，值为gateway。
      #而从其它地方到达微服务的请求则没有这个头。
      default-filters:
        - AddRequestHeader=origin,gateway
      routes: # 网关路由配置
        - id: music-service
          uri: lb://music-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/musics/**,/comments/**,/likes/**,/collections/**

        - id: songlist-service
          uri: lb://songlist-service
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/songlists/**,/songlist-musics/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/users/**,/email/**

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

logging:
  level:
    org.springframework.cloud.gateway: TRACE