spring:
  application:
    name: eventservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memorandum
    username: root
    password: "@Aa123456"
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: FJ # 集群名称
eventservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
swagger:
  title: "备忘录事件"
  description: "备忘录事件"
  base-package: com.flyingpig.memorandumevent
  enabled: true
  version: 1.0.0


