#端口配置
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
#spring配置
spring:
  application:
    name: songlist-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.173.12:3306/cloudmusic
    username: root
    password: "@Aa123456"
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        cluster-name: FJ # 集群名称
        ip: localhost # 注册到nacos的ip与端口
        port: 8082
#ribbon配置
songlistservice:
    ribbon:
      NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
#mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#swagger
swagger:
  title: "歌单模块"
  description: "歌单模块接口"
  base-package: com.flyingpig.cloudmusic.songlist
  enabled: true
  version: 1.0.0
#feign远程调用配置
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  sentinel:
    enabled: true

