#运行端口
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
#spring配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: music-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.173.12:3306/cloudmusic
    username: root
    password: "@Aa123456"
  redis:
    database: 0
    host: localhost
    port: 6379
  cloud:
    nacos:
      server-addr: http://47.122.56.65:8848
      discovery:
        cluster-name: FJ # 集群名称
        ip: 111.229.173.12 # 注册到nacos的ip与端口
        port: 9090
#ribbon配置
music-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
#持久层配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#swagger配置
swagger:
  title: "音乐模块"
  description: "音乐模块接口"
  base-package: com.flyingpig.cloudmusic
  enabled: true
  version: 1.0.0
#feign远程调用配置
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数


